meilisearch:
    url: 'http://127.0.0.1:7700' # URL of the Meilisearch server (mandatory)
    api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
    prefix: '%env(MEILISEARCH_PREFIX)%'
    nbResults: 36 # Retrieve fewer results on search (default: 20)
    indices:
        # Define entities or documents that should be indexed to Meilisearch.
        # See https://github.com/meilisearch/meilisearch-symfony/wiki/configure-searchable-data
        - name: books
          class: App\Entity\Book
          enable_serializer_groups: true
          serializer_groups: ['searchable']