name: Tests
on: [push, pull_request]
jobs: 
  quality:
    name: Tests
    runs-on: ubuntu-latest
    services:
      meilisearch:
        image: getmeili/meilisearch:v1.0
        ports:
          - 7700:7700
        env:
          MEILI_MASTER_KEY: '!ChangeMe!'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching deps
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Update composer
        run: composer self-update
        env:
          DATABASE_URL: "mysql://root:root@database:3306/neobook?serverVersion=8.0.32&charset=utf8mb4"

      - name: Install MySQL
        run: sudo apt-get update && sudo apt-get install -y mysql-server

      - name: Start MySQL
        run: sudo service mysql start

      - name: Secure MySQL Installation
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root'; FLUSH PRIVILEGES;"

      - name: Configure MySQL
        run: |
          mysql -uroot -proot -e "CREATE DATABASE neobook;"
          mysql -uroot -proot -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
          mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON neobook.* TO 'root'@'localhost';"
          mysql -uroot -proot -e "FLUSH PRIVILEGES;"

      - name: install deps
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 --user=root --password=root --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Tests
        run: composer test
        env:
          APP_ENV: TEST
          APP_DEBUG: true
          XDEBUG_MODE: coverage
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/neobook?serverVersion=8.0.32&charset=utf8mb4"
          MEILI_HTTP_ADDR: http://meilisearch:7700
          MEILI_MASTER_KEY: '!ChangeMe!'

        
    