name: Tests
on: [push, pull_request]
jobs: 
  quality:
    name: Tests
    runs-on: ubuntu-latest
    services:
      meilisearch:
        image: getmeili/meilisearch:v1.0
        ports:
          - 7700:7700
        env:
          MEILI_MASTER_KEY: '!ChangeMe!'

      database:
        image: mysql:8.0.32
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: neobook
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      phpmyadmin:
        image: phpmyadmin:5.2.2
        ports:
          - 8080:80
        env:
          PMA_HOST: database
          PMA_PORT: 3306
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: Setup Cache
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

      - name: Caching deps
        uses: actions/cache@v4
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php8.3-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            php8.3-composer-latest-

      - name: Update composer
        run: composer self-update
        env:
          DATABASE_URL: "mysql://root@database:3306/neobook?serverVersion=8.0.32&charset=utf8mb4"

      - name: install deps
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h database --user=root --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Tests
        run: composer test
        env:
          APP_ENV: TEST
          APP_DEBUG: true
          XDEBUG_MODE: coverage
          DATABASE_URL: "mysql://root@database:3306/neobook?serverVersion=8.0.32&charset=utf8mb4"
          MEILI_HTTP_ADDR: http://meilisearch:7700
          MEILI_MASTER_KEY: '!ChangeMe!'

        
    